/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
#include <stdio.h>
#include <stdlib.h>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <iostream>
#include <android/log.h>
#include <vector>
#include <algorithm>
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>

using namespace cv;
using namespace std;


/* Header for class com_estrada_examen_MyNdk */

#ifndef _Included_com_estrada_examen_MyNdk
#define _Included_com_estrada_examen_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_estrada_examen_MyNdk
 * Method:    getMyString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_estrada_examen_MyNdk_getMyString
  (JNIEnv *env, jobject);

JNIEXPORT void JNICALL Java_com_estrada_examen_MyNdk_modifyInstanceVariable(JNIEnv *env, jobject obj,jstring text);

JNIEXPORT jintArray JNICALL Java_com_estrada_examen_MyNdk_prueba(JNIEnv *env, jobject obj, jint size);

JNIEXPORT jintArray JNICALL Java_com_estrada_examen_MyNdk_resultado(JNIEnv *env, jobject obj, jlong addrRgba);

JNIEXPORT jint JNICALL Java_com_estrada_examen_MyNdk_suma
    (JNIEnv *env, jobject, jint num);


JNIEXPORT void JNICALL Java_com_estrada_examen_MyNdk_detect
    (JNIEnv *env, jobject obj, jlong addrRgba);

JNIEXPORT void JNICALL Java_com_estrada_examen_MyNdk_black
(JNIEnv *env, jobject obj, jlong addrRgba);

JNIEXPORT jint JNICALL Java_com_estrada_examen_MyNdk_convertGray
        (JNIEnv *env, jobject, jlong addrRgba, jlong addrGray);

jint factorial(jint n);
int toGray(Mat img, Mat& gray);
cv::Point2f computeIntersect(cv::Vec4i a, cv::Vec4i b);
bool comparator2(double a, double b);
bool comparator3(Vec3f a, Vec3f b);
bool comparator(Point2f a, Point2f b);
void sortCorners(std::vector<cv::Point2f>& corners, cv::Point2f center);
void detect(Mat& quad,JNIEnv *env, jobject obj);
void black(Mat& img);
jstring int_array_to_string(int int_array[], int size_of_array, JNIEnv *env);
void ModifyString(JNIEnv *env, jobject obj, jstring texto);

#ifdef __cplusplus
}
#endif
#endif
